/*
SPAMDA: Software for Pre-processing and Analysis of Meteorological DAta to build datasets

Copyright (c) 2017-2021 by AYRNA Research Group. https://www.uco.es/ayrna/
    Authors: 
      Gómez-Orellana, A.M.; Fernández, J.C.; Dorado-Moreno, M.; Gutiérrez, P.A.; Hervás-Martínez, C.
      Building Suitable Datasets for Soft Computing and Machine Learning Techniques from Meteorological
       Data Integration: A Case Study for Predicting Significant Wave Height and Energy Flux.
      Energies 2021, 14, 468. https://doi.org/10.3390/en14020468                                                                       

This program is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program,
in the file COPYING. If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7:
1. Redistributions of source code, with or without modification, must retain
the above full copyright notice as author attributions.

2. Redistributions in binary form and/or the use of the documentation,
with or without modification, must reproduce the above full copyright notice
as author attributions in the documentation and/or materials provided with
the distribution.

3. Modified versions of source code and/or documentation, as well as binary
distributions, must be marked in reasonable ways as different from the original version.

4. Neither name of copyright holders nor the names of its contributors may be used
to endorse or promote products derived from this software for publicity purposes
without specific prior written permission.

5. Redistribution and/or use of source code, binary format and documentation,
with or without modification, could require indemnification of licensors
and authors by anyone who conveys the material (or modified versions of it)
with contractual assumptions of liability to the recipient, for any liability
that these contractual assumptions directly impose on those licensors and authors.

SPAMDA uses some external libraries. You can see their respective notices about license,
copyright and disclaimer in the following files. For a more complete information about
such licenses, see the distributions provided by their authors:
-Library NetCDF Java, version 4.6.10
	Notice of license in the file NetCDF-LICENSE
-Library SLF4J, version 1.7.25
	Notice of license in the file SLF4J-LICENSE
-Library WEKA, version 3.8.1
	Notice of license in the file WEKA-LICENSE

Contact information:
Antonio Manuel Gomez Orellana, Mr.
email: am[dot]gomez[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).

Juan Carlos Fernandez Caballero, PhD.
email: jfcaballero[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).
 */

package view;

import controller.ControllerViewAbout;
import view.interfaces.InterfaceViewAbout;
import java.awt.Insets;


/**
 * This class defines the view that shows the information of development group of the application.
 * 
 */
public class About extends javax.swing.JDialog implements InterfaceViewAbout {
    
    /* Generated by NetBeans. */
    private static final long serialVersionUID = -8327929087412825297L;

    
    /**
     * Creates new dialog About
     * 
     * @param parent Jframe that creates this dialog.
     * @param modal Indicates if the dialog is modal or not.
     */
    public About(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        
        /* Sets the link to UCO website in html format. */        
        btnWebSiteUCO.setText("<html><a href=\"\">" + "http://www.uco.es" + "</a></html>");
        
        /* Sets the link to DIAN website in html format. */
        btnWebSiteDIAN.setText("<html><a href=\"\">" + "http://www.uco.es/dptos/dian" + "</a></html>");        

        /* Sets the link to AYRNA Group website in html format. */                
        btnWebSiteAyrnaGroup.setText("<html><a href=\"\">" + "http://www.uco.es/ayrna" + "</a></html>");
        
        
        /* Sets the action that controller will recognised. */
        btnWebSiteUCO.setActionCommand("WebSiteUCO");
                
        /* Sets the action that controller will recognised. */
        btnWebSiteDIAN.setActionCommand("WebSiteDIAN");
        
        /* Sets the action that controller will recognised. */
        btnWebSiteAyrnaGroup.setActionCommand("WebSiteAYRNAGroup");
        
        
        /* WebSite UCO button looks like a jLabel. */        
        btnWebSiteUCO.setFocusPainted(false);
        btnWebSiteUCO.setMargin(new Insets(0, 0, 0, 0));
        btnWebSiteUCO.setContentAreaFilled(false);
        btnWebSiteUCO.setBorderPainted(false);
        btnWebSiteUCO.setOpaque(false);
        
        /* WebSite DIAN button looks like a jLabel. */        
        btnWebSiteAyrnaGroup.setFocusPainted(false);
        btnWebSiteAyrnaGroup.setMargin(new Insets(0, 0, 0, 0));
        btnWebSiteAyrnaGroup.setContentAreaFilled(false);
        btnWebSiteAyrnaGroup.setBorderPainted(false);
        btnWebSiteAyrnaGroup.setOpaque(false);

        /* WebSite AYRNA Group button looks like a jLabel. */        
        btnWebSiteDIAN.setFocusPainted(false);
        btnWebSiteDIAN.setMargin(new Insets(0, 0, 0, 0));
        btnWebSiteDIAN.setContentAreaFilled(false);
        btnWebSiteDIAN.setBorderPainted(false);
        btnWebSiteDIAN.setOpaque(false);
                
    }

    
    /* Methods of InterfaceViewAbout */

    

    @Override
    public void setController(ControllerViewAbout controller){
        
        /* Buttons. */        
        btnWebSiteUCO.addActionListener(controller);
        btnWebSiteAyrnaGroup.addActionListener(controller);
        btnWebSiteDIAN.addActionListener(controller);

    }

    
    @Override
    public void showView(){
        
        /* Shows the view. */    
        this.setVisible(true);
    
    }

    
    @Override
    public void closeView(){
    
        /* Closes the view. */
        this.dispose();
        
    }


    @Override
    public String getWebSiteUCO(){
        
        /* Gets UCO's URL to open with default browser. */
        return "http://www.uco.es/";
    
    }
    
    
    @Override
    public String getWebSiteDIAN(){
        
        /* Gets DIAN's URL to open with default browser. */
        return "http://www.uco.es/dptos/dian/";
    
    }
    
    
    @Override
    public String getWebSiteAYRNAGroup(){
        
        /* Gets AYRNA Group's URL to open with default browser. */
        return "http://www.uco.es/ayrna/";
    
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnWebSiteUCO = new javax.swing.JButton();
        btnWebSiteDIAN = new javax.swing.JButton();
        btnWebSiteAyrnaGroup = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        lblUCO = new javax.swing.JLabel();
        lblDIAN = new javax.swing.JLabel();
        lblAyrnaGroup = new javax.swing.JLabel();
        lblDIAN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        btnWebSiteUCO.setText("WebSite");
        btnWebSiteUCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnWebSiteDIAN.setText("WebSite");
        btnWebSiteDIAN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnWebSiteAyrnaGroup.setText("WebSite");
        btnWebSiteAyrnaGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDescription.setText("Software for Pre-processing and Analysis of");

        lblDescription1.setText("Meteorological DAta to build datasets (SPAMDA 1.0)");

        lblUCO.setText("University of Córdoba (Spain)");

        lblDIAN.setText("Department of Computer Science and");

        lblAyrnaGroup.setText("AYRNA Research Group");

        lblDIAN1.setText("Numerical Analysis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUCO)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblDIAN1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblAyrnaGroup)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWebSiteUCO)
                            .addComponent(btnWebSiteDIAN)
                            .addComponent(btnWebSiteAyrnaGroup)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblDIAN)
                        .addGap(0, 207, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblDescription1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblDescription)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblDescription)
                .addGap(6, 6, 6)
                .addComponent(lblDescription1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUCO)
                            .addComponent(btnWebSiteUCO))
                        .addGap(24, 24, 24)
                        .addComponent(lblDIAN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDIAN1))
                    .addComponent(btnWebSiteDIAN))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAyrnaGroup)
                    .addComponent(btnWebSiteAyrnaGroup))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWebSiteAyrnaGroup;
    private javax.swing.JButton btnWebSiteDIAN;
    private javax.swing.JButton btnWebSiteUCO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAyrnaGroup;
    private javax.swing.JLabel lblDIAN;
    private javax.swing.JLabel lblDIAN1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblUCO;
    // End of variables declaration//GEN-END:variables
}
