/*
SPAMDA: Software for Pre-processing and Analysis of Meteorological DAta to build datasets

Copyright (c) 2017-2018 by AYRNA Research Group. https://www.uco.es/ayrna/
	Authors: 
		Antonio Manuel Gomez Orellana, Juan Carlos Fernandez Caballero,
		Manuel Dorado Moreno, Pedro Antonio Gutierrez Peña and 
		Cesar Hervas Martinez.

This program is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program,
in the file COPYING. If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7:
1. Redistributions of source code, with or without modification, must retain
the above full copyright notice as author attributions.

2. Redistributions in binary form and/or the use of the documentation,
with or without modification, must reproduce the above full copyright notice
as author attributions in the documentation and/or materials provided with
the distribution.

3. Modified versions of source code and/or documentation, as well as binary
distributions, must be marked in reasonable ways as different from the original version.

4. Neither name of copyright holders nor the names of its contributors may be used
to endorse or promote products derived from this software for publicity purposes
without specific prior written permission.

5. Redistribution and/or use of source code, binary format and documentation,
with or without modification, could require indemnification of licensors
and authors by anyone who conveys the material (or modified versions of it)
with contractual assumptions of liability to the recipient, for any liability
that these contractual assumptions directly impose on those licensors and authors.

SPAMDA uses some external libraries. You can see their respective notices about license,
copyright and disclaimer in the following files. For a more complete information about
such licenses, see the distributions provided by their authors:
-Library NetCDF Java, version 4.6.10
	Notice of license in the file NetCDF-LICENSE
-Library SLF4J, version 1.7.25
	Notice of license in the file SLF4J-LICENSE
-Library WEKA, version 3.8.1
	Notice of license in the file WEKA-LICENSE

Contact information:
Juan Carlos Fernandez Caballero, PhD.
email: jfcaballero[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).
 */

package view;

import controller.ControllerViewDatasetFileConverter;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import view.interfaces.InterfaceViewDatasetFileConverter;

/**
 * This class defines the view to convert an intermediate or pre-processed dataset file into CSV or ARFF format.
 * 
 */
public class DatasetFileConverter extends javax.swing.JDialog implements InterfaceViewDatasetFileConverter {
            
    /* Generated by NetBeans. */
    private static final long serialVersionUID = -3473106874960842214L;
    

    /**
     * Creates new dialog DatasetFileConverter
     * 
     * @param parent Jframe that creates this dialog.
     * @param modal Indicates if the dialog is modal or not.
     */
    public DatasetFileConverter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        /* Sets columns size (grid with information about buoys.). */
        tblBuoys.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblBuoys.getColumnModel().getColumn(1).setPreferredWidth(192);

        /* When sets the datamodel will only show the columns created in the view. */
        tblBuoys.setAutoCreateColumnsFromModel(false);        
        
    }
    
    
    /* Methods of InterfaceViewDatasetFileConverter */

    
    @Override
    public void setController(ControllerViewDatasetFileConverter controller){
        
        /* Buttons. */
        btnMainMenu.addActionListener(controller);
        btnConvertDatasetToARFF.addActionListener(controller);
        btnConvertDatasetToCSV.addActionListener(controller);
        btnConvertPreprocessedToARFF.addActionListener(controller);
        btnConvertPreprocessedToCSV.addActionListener(controller);

        
        /* Menu items. */        
        itemMainMenu.addActionListener(controller);        
        itemHelpManual.addActionListener(controller);
        
        
        /* Tables. */
        tblBuoys.getSelectionModel().addListSelectionListener(controller);

        
        /* List. */
        jlstDatasetFiles.addListSelectionListener(controller);
        jlstPreprocessedDataset.addListSelectionListener(controller);        
                
    }

    
    @Override
    public void showView(){
        
        /* Shows the view. */
        
        this.setVisible(true);
    
    }

    
    @Override
    public void closeView(){
    
        /* Closes the view. */
        this.dispose();
        
    }

    
    @Override
    public DefaultTableModel getModelBuoys(){
    
        /* Returns DefaultTableModel of the table that will show the id and name about each buoy. */
        return (DefaultTableModel) tblBuoys.getModel();
        
    }
    
    
    @Override
    public void setModelBuoys(DefaultTableModel datamodel){
        
        /* Shows the StationID of each buoy. */
        
        tblBuoys.setModel(datamodel);
        
    }

    
    @Override
    public int getSelectedRowBuoy(){
        
        /* Gets the selected row to show all dataset files that belong to the buoy. */
        
        return tblBuoys.getSelectedRow();
    
    }

    
    @Override
    public void setModelDatasets(DefaultListModel<String> listmodel){
        
        /* Shows the dataset files that belong to the buoy. */
        
        jlstDatasetFiles.setModel(listmodel);      
        
    }

    
    @Override
    public void setModelPreprocessedDatasets(DefaultListModel<String> listmodel){
        
        /* Shows the preprocessed files that belong to the selected dataset file and buoy. */
        
        jlstPreprocessedDataset.setModel(listmodel);      
        
    }
    
        
    @Override
    public int getSelectedIndexDataset(){
        
        /* Gets the selected dataset file. */
        
        return jlstDatasetFiles.getSelectedIndex();
    
    }
    
    @Override
    public int getSelectedIndexPreprocessedDataset(){
        
        /* Gets the selected preprocessed dataset file. */
        
        return jlstPreprocessedDataset.getSelectedIndex();
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JButton();
        jscrBuoys = new javax.swing.JScrollPane();
        tblBuoys = new javax.swing.JTable();
        jpnDatasetFiles = new javax.swing.JPanel();
        jscrDatasetFiles = new javax.swing.JScrollPane();
        jlstDatasetFiles = new javax.swing.JList<>();
        btnConvertDatasetToARFF = new javax.swing.JButton();
        btnConvertDatasetToCSV = new javax.swing.JButton();
        jpnPreprocessedDataset = new javax.swing.JPanel();
        jscrPreprocessedDataset = new javax.swing.JScrollPane();
        jlstPreprocessedDataset = new javax.swing.JList<>();
        btnConvertPreprocessedToARFF = new javax.swing.JButton();
        btnConvertPreprocessedToCSV = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        itemMainMenu = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        itemHelpManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPAMDA 1.0-Dataset converter");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        btnMainMenu.setText("Main menu");
        btnMainMenu.setToolTipText("Back to Main menu");

        jscrBuoys.setBorder(null);

        tblBuoys.setBorder(null);
        tblBuoys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Station ID"
            }
        ) {

            /* Generated by NetBeans. */
            private static final long serialVersionUID = -1006288877740180822L;

            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBuoys.setToolTipText("Select a buoy to show intermediate datasets");
        tblBuoys.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBuoys.getTableHeader().setReorderingAllowed(false);
        jscrBuoys.setViewportView(tblBuoys);
        if (tblBuoys.getColumnModel().getColumnCount() > 0) {
            tblBuoys.getColumnModel().getColumn(0).setMinWidth(0);
            tblBuoys.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblBuoys.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jpnDatasetFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("Intermediate datasets"));

        jlstDatasetFiles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlstDatasetFiles.setToolTipText("Click to select the intermediate dataset");
        jlstDatasetFiles.setName("jlstDatasetFiles"); // NOI18N
        jscrDatasetFiles.setViewportView(jlstDatasetFiles);
        jlstDatasetFiles.getAccessibleContext().setAccessibleName("jlstDatasetFiles");
        jlstDatasetFiles.getAccessibleContext().setAccessibleDescription("");

        btnConvertDatasetToARFF.setText("Convert to ARFF");
        btnConvertDatasetToARFF.setToolTipText("Convert the intermediate dataset to ARFF format");
        btnConvertDatasetToARFF.setActionCommand("Convert dataset to ARFF");

        btnConvertDatasetToCSV.setText("Convert to CSV");
        btnConvertDatasetToCSV.setToolTipText("Convert the intermediate dataset to CSV format");
        btnConvertDatasetToCSV.setActionCommand("Convert dataset to CSV");

        javax.swing.GroupLayout jpnDatasetFilesLayout = new javax.swing.GroupLayout(jpnDatasetFiles);
        jpnDatasetFiles.setLayout(jpnDatasetFilesLayout);
        jpnDatasetFilesLayout.setHorizontalGroup(
            jpnDatasetFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDatasetFilesLayout.createSequentialGroup()
                .addComponent(jscrDatasetFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDatasetFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvertDatasetToARFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvertDatasetToCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDatasetFilesLayout.setVerticalGroup(
            jpnDatasetFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrDatasetFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpnDatasetFilesLayout.createSequentialGroup()
                .addComponent(btnConvertDatasetToARFF)
                .addGap(18, 18, 18)
                .addComponent(btnConvertDatasetToCSV))
        );

        jpnPreprocessedDataset.setBorder(javax.swing.BorderFactory.createTitledBorder("Pre-processed datasets"));

        jlstPreprocessedDataset.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlstPreprocessedDataset.setToolTipText("Click to select the pre-processed dataset");
        jlstPreprocessedDataset.setName("jlstPreprocessedDataset"); // NOI18N
        jscrPreprocessedDataset.setViewportView(jlstPreprocessedDataset);
        jlstPreprocessedDataset.getAccessibleContext().setAccessibleName("jlstPreprocessFiles");

        btnConvertPreprocessedToARFF.setText("Convert to ARFF");
        btnConvertPreprocessedToARFF.setToolTipText("Convert the pre-processed dataset to ARFF format");
        btnConvertPreprocessedToARFF.setActionCommand("Convert preprocessed to ARFF");

        btnConvertPreprocessedToCSV.setText("Convert to CSV");
        btnConvertPreprocessedToCSV.setToolTipText("Convert the pre-processed dataset to CSV format");
        btnConvertPreprocessedToCSV.setActionCommand("Convert preprocessed to CSV");

        javax.swing.GroupLayout jpnPreprocessedDatasetLayout = new javax.swing.GroupLayout(jpnPreprocessedDataset);
        jpnPreprocessedDataset.setLayout(jpnPreprocessedDatasetLayout);
        jpnPreprocessedDatasetLayout.setHorizontalGroup(
            jpnPreprocessedDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPreprocessedDatasetLayout.createSequentialGroup()
                .addComponent(jscrPreprocessedDataset, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnPreprocessedDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvertPreprocessedToARFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvertPreprocessedToCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPreprocessedDatasetLayout.setVerticalGroup(
            jpnPreprocessedDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrPreprocessedDataset, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpnPreprocessedDatasetLayout.createSequentialGroup()
                .addComponent(btnConvertPreprocessedToARFF)
                .addGap(18, 18, 18)
                .addComponent(btnConvertPreprocessedToCSV))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jscrBuoys, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpnDatasetFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnPreprocessedDataset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jpnDatasetFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnPreprocessedDataset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jscrBuoys, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMainMenu)
                .addContainerGap())
        );

        jmMenu.setText("Menu");

        itemMainMenu.setText("Main menu");
        itemMainMenu.setToolTipText("Back to Main menu.");
        jmMenu.add(itemMainMenu);

        jMenuBar.add(jmMenu);

        jmHelp.setText("Help");

        itemHelpManual.setText("Help (User manual)");
        jmHelp.add(itemHelpManual);

        jMenuBar.add(jmHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertDatasetToARFF;
    private javax.swing.JButton btnConvertDatasetToCSV;
    private javax.swing.JButton btnConvertPreprocessedToARFF;
    private javax.swing.JButton btnConvertPreprocessedToCSV;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JMenuItem itemHelpManual;
    private javax.swing.JMenuItem itemMainMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JList<String> jlstDatasetFiles;
    private javax.swing.JList<String> jlstPreprocessedDataset;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JPanel jpnDatasetFiles;
    private javax.swing.JPanel jpnPreprocessedDataset;
    private javax.swing.JScrollPane jscrBuoys;
    private javax.swing.JScrollPane jscrDatasetFiles;
    private javax.swing.JScrollPane jscrPreprocessedDataset;
    private javax.swing.JTable tblBuoys;
    // End of variables declaration//GEN-END:variables
}
