/*
SPAMDA: Software for Pre-processing and Analysis of Meteorological DAta to build datasets

Copyright (c) 2017-2018 by AYRNA Research Group. https://www.uco.es/ayrna/
	Authors: 
		Antonio Manuel Gomez Orellana, Juan Carlos Fernandez Caballero,
		Manuel Dorado Moreno, Pedro Antonio Gutierrez Peña and 
		Cesar Hervas Martinez.

This program is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program,
in the file COPYING. If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7:
1. Redistributions of source code, with or without modification, must retain
the above full copyright notice as author attributions.

2. Redistributions in binary form and/or the use of the documentation,
with or without modification, must reproduce the above full copyright notice
as author attributions in the documentation and/or materials provided with
the distribution.

3. Modified versions of source code and/or documentation, as well as binary
distributions, must be marked in reasonable ways as different from the original version.

4. Neither name of copyright holders nor the names of its contributors may be used
to endorse or promote products derived from this software for publicity purposes
without specific prior written permission.

5. Redistribution and/or use of source code, binary format and documentation,
with or without modification, could require indemnification of licensors
and authors by anyone who conveys the material (or modified versions of it)
with contractual assumptions of liability to the recipient, for any liability
that these contractual assumptions directly impose on those licensors and authors.

SPAMDA uses some external libraries. You can see their respective notices about license,
copyright and disclaimer in the following files. For a more complete information about
such licenses, see the distributions provided by their authors:
-Library NetCDF Java, version 4.6.10
	Notice of license in the file NetCDF-LICENSE
-Library SLF4J, version 1.7.25
	Notice of license in the file SLF4J-LICENSE
-Library WEKA, version 3.8.1
	Notice of license in the file WEKA-LICENSE

Contact information:
Juan Carlos Fernandez Caballero, PhD.
email: jfcaballero[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).
 */

package view;

import controller.ControllerViewOpenARFFfile;
import view.interfaces.InterfaceViewOpenARFFfile;

/**
 * This class defines the view to open an ARFF file with WEKA tool.
 * 
 */

public class OpenARFFfile extends javax.swing.JDialog implements InterfaceViewOpenARFFfile {
        
    /* Generated by NetBeans. */
    private static final long serialVersionUID = -8581317834872999328L;

    
    /**
     * Creates new dialog OpenARFFfile
     * 
     * @param parent Jframe that creates this dialog.
     * @param modal Indicates if the dialog is modal or not.
     */
    public OpenARFFfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    
    /* Methods of InterfaceViewOpenARFFfile */

    
    @Override
    public void setController(ControllerViewOpenARFFfile controller){
        
        /* Buttons. */
        btnOpenFile.addActionListener(controller);        
        btnARFFBrowse.addActionListener(controller);
        btnMainMenu.addActionListener(controller);
        
        /* Menu items. */        
        itemMainMenu.addActionListener(controller);        
        itemHelpManual.addActionListener(controller);
    
    }

    
    @Override
    public void showView(){
        
        /* Shows the view. */    
        this.setVisible(true);
    
    }

    
    @Override
    public void closeView(){
    
        /* Closes the view. */
        this.dispose();
        
    }


    @Override
    public String getARFFfilename(){
        
        /* Gets the ARFF file name to open. */
        return jtfPathARFFfile.getText();
    
    }


    @Override
    public void setARFFfilename(String filename){
        
        /* Sets the ARFF file name to open. */
        jtfPathARFFfile.setText(filename);
    
    }
    
    
    @Override
    public void setEnableBtnOpenFile(boolean state){
        
        /* Sets button btnOpen enabled or disabled. */    
        btnOpenFile.setEnabled(state);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arffFileChooser = new javax.swing.JFileChooser();
        jPanel = new javax.swing.JPanel();
        btnOpenFile = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        jpnARFFFile = new javax.swing.JPanel();
        jtfPathARFFfile = new javax.swing.JTextField();
        btnARFFBrowse = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        itemMainMenu = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        itemHelpManual = new javax.swing.JMenuItem();

        arffFileChooser.setFileFilter(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPAMDA 1.0-Open ARFF file with WEKA");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        btnOpenFile.setText("Open file");
        btnOpenFile.setToolTipText("Open ARFF file with WEKA");
        btnOpenFile.setEnabled(false);

        btnMainMenu.setText("Main menu");
        btnMainMenu.setToolTipText("Back to Main menu");

        jpnARFFFile.setBorder(javax.swing.BorderFactory.createTitledBorder("ARFF file to open"));

        jtfPathARFFfile.setEditable(false);
        jtfPathARFFfile.setToolTipText("Selected file to open");

        btnARFFBrowse.setText("Browse...");
        btnARFFBrowse.setToolTipText("Browse ARFF files");

        javax.swing.GroupLayout jpnARFFFileLayout = new javax.swing.GroupLayout(jpnARFFFile);
        jpnARFFFile.setLayout(jpnARFFFileLayout);
        jpnARFFFileLayout.setHorizontalGroup(
            jpnARFFFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnARFFFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPathARFFfile, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnARFFBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnARFFFileLayout.setVerticalGroup(
            jpnARFFFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnARFFFileLayout.createSequentialGroup()
                .addGroup(jpnARFFFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPathARFFfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnARFFBrowse))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnARFFFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnARFFFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenFile)
                    .addComponent(btnMainMenu))
                .addContainerGap())
        );

        jmMenu.setText("Menu");

        itemMainMenu.setText("Main menu");
        jmMenu.add(itemMainMenu);

        jMenuBar.add(jmMenu);

        jmHelp.setText("Help");

        itemHelpManual.setText("Help (User manual)");
        jmHelp.add(itemHelpManual);

        jMenuBar.add(jmHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser arffFileChooser;
    private javax.swing.JButton btnARFFBrowse;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JMenuItem itemHelpManual;
    private javax.swing.JMenuItem itemMainMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JPanel jpnARFFFile;
    private javax.swing.JTextField jtfPathARFFfile;
    // End of variables declaration//GEN-END:variables
}
