/*
SPAMDA: Software for Pre-processing and Analysis of Meteorological DAta to build datasets

Copyright (c) 2017-2021 by AYRNA Research Group. https://www.uco.es/ayrna/
    Authors: 
      Gómez-Orellana, A.M.; Fernández, J.C.; Dorado-Moreno, M.; Gutiérrez, P.A.; Hervás-Martínez, C.
      Building Suitable Datasets for Soft Computing and Machine Learning Techniques from Meteorological
       Data Integration: A Case Study for Predicting Significant Wave Height and Energy Flux.
      Energies 2021, 14, 468. https://doi.org/10.3390/en14020468                                                                       

This program is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program,
in the file COPYING. If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7:
1. Redistributions of source code, with or without modification, must retain
the above full copyright notice as author attributions.

2. Redistributions in binary form and/or the use of the documentation,
with or without modification, must reproduce the above full copyright notice
as author attributions in the documentation and/or materials provided with
the distribution.

3. Modified versions of source code and/or documentation, as well as binary
distributions, must be marked in reasonable ways as different from the original version.

4. Neither name of copyright holders nor the names of its contributors may be used
to endorse or promote products derived from this software for publicity purposes
without specific prior written permission.

5. Redistribution and/or use of source code, binary format and documentation,
with or without modification, could require indemnification of licensors
and authors by anyone who conveys the material (or modified versions of it)
with contractual assumptions of liability to the recipient, for any liability
that these contractual assumptions directly impose on those licensors and authors.

SPAMDA uses some external libraries. You can see their respective notices about license,
copyright and disclaimer in the following files. For a more complete information about
such licenses, see the distributions provided by their authors:
-Library NetCDF Java, version 4.6.10
	Notice of license in the file NetCDF-LICENSE
-Library SLF4J, version 1.7.25
	Notice of license in the file SLF4J-LICENSE
-Library WEKA, version 3.8.1
	Notice of license in the file WEKA-LICENSE

Contact information:
Antonio Manuel Gomez Orellana, Mr.
email: am[dot]gomez[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).

Juan Carlos Fernandez Caballero, PhD.
email: jfcaballero[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).
 */

package view;

import controller.ControllerViewSelectBuoyAttributes;
import javax.swing.table.DefaultTableModel;
import view.interfaces.InterfaceViewSelectBuoyAttributes;

/**
 * This class defines the view to select the attributes of the buoy to use in the matching process.
 * 
 */
public class SelectBuoyAttributes extends javax.swing.JDialog implements InterfaceViewSelectBuoyAttributes {

    /* Generated by NetBeans. */
    private static final long serialVersionUID = -6926670346696208290L;
    

    /**
     * Creates new dialog SelectBuoyAttributes
     * 
     * @param parent Jframe that creates this dialog.
     * @param modal Indicates if the dialog is modal or not.
     */
    public SelectBuoyAttributes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                        
    }
    
    
    /* Methods of InterfaceViewSelectBuoyAttributes */

    

    @Override
    public void setController(ControllerViewSelectBuoyAttributes controller){
        
        /* Buttons. */
        btnIncludeAll.addActionListener(controller);        
        btnClearSelection.addActionListener(controller);
        btnBack.addActionListener(controller);
        btnConfirmSelection.addActionListener(controller);
        
        /* Menu items. */        
        itemBack.addActionListener(controller);        
        itemHelpManual.addActionListener(controller);
        
        /* Tables. */
        tblBuoyVariables.addMouseListener(controller);
                                        
    }

    
    @Override
    public void showView(){
        
        /* Shows the view. */
        
        this.setVisible(true);
    
    }

    
    @Override
    public void closeView(){
    
        /* Closes the view. */
        this.dispose();
        
    }
    
    
    @Override
    public DefaultTableModel getModelBuoyAttributes(){
    
        /* Returns the model of the table that shows the variables of the buoy. */
        return (DefaultTableModel) tblBuoyVariables.getModel();
        
    }
    
    
    @Override
    public void setModelBuoyAttributes(DefaultTableModel datamodel){
        
        /* Shows the information received about each variable of the buoy. */
        
        tblBuoyVariables.setModel(datamodel);
        
    }
                              
    
    @Override
    public void tblBuoyAttributesRepaint(){
        
        /* Repaints tblBuoyVariables. */
        
        tblBuoyVariables.repaint();
        
    }
            
    
    @Override
    public int getSelectedRow(){
        
        /* Gets the selected row. */
        
        return tblBuoyVariables.getSelectedRow();
    
    }
    
    
    @Override
    public int getSelectedColumn(){
        
        /* Gets the selected column. */
        
        return tblBuoyVariables.getSelectedColumn();
    
    }
    
                 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jpnBuoyVariables = new javax.swing.JPanel();
        jscrBuoyVariables = new javax.swing.JScrollPane();
        tblBuoyVariables = new javax.swing.JTable();
        btnClearSelection = new javax.swing.JButton();
        btnIncludeAll = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnConfirmSelection = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        itemBack = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        itemHelpManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPAMDA 1.0-Select buoys attributes");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        jpnBuoyVariables.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes of the buoy"));

        jscrBuoyVariables.setBorder(null);

        tblBuoyVariables.setBorder(null);
        tblBuoyVariables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selected", "Name of the attribute"
            }
        ) {

            /* Generated by NetBeans. */
            private static final long serialVersionUID = -6158042587124966771L;

            Class<?>[] types = new Class<?> [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBuoyVariables.setToolTipText("Double click to select or deselect the attribute of the buoy");
        tblBuoyVariables.setName("tblBuoyVariables"); // NOI18N
        tblBuoyVariables.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBuoyVariables.getTableHeader().setReorderingAllowed(false);
        jscrBuoyVariables.setViewportView(tblBuoyVariables);

        btnClearSelection.setText("Clear selection");
        btnClearSelection.setToolTipText("Clear current selection");

        btnIncludeAll.setText("Select all");
        btnIncludeAll.setToolTipText("Select all the attributes of the buoy");

        javax.swing.GroupLayout jpnBuoyVariablesLayout = new javax.swing.GroupLayout(jpnBuoyVariables);
        jpnBuoyVariables.setLayout(jpnBuoyVariablesLayout);
        jpnBuoyVariablesLayout.setHorizontalGroup(
            jpnBuoyVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBuoyVariablesLayout.createSequentialGroup()
                .addComponent(jscrBuoyVariables, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnBuoyVariablesLayout.createSequentialGroup()
                .addComponent(btnClearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncludeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnBuoyVariablesLayout.setVerticalGroup(
            jpnBuoyVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBuoyVariablesLayout.createSequentialGroup()
                .addComponent(jscrBuoyVariables, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpnBuoyVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearSelection)
                    .addComponent(btnIncludeAll))
                .addGap(4, 4, 4))
        );

        btnClearSelection.getAccessibleContext().setAccessibleDescription("Delete selected matching file.");

        btnBack.setText("Back");
        btnBack.setToolTipText("Back to Matching configuration");

        btnConfirmSelection.setText("Confirm selection");
        btnConfirmSelection.setToolTipText("Confirm attributes selection and back to Matching configuration");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnBuoyVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnBuoyVariables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmSelection)
                    .addComponent(btnBack)))
        );

        jmMenu.setText("Menu");

        itemBack.setText("Back");
        itemBack.setToolTipText("Back to Matching configuration");
        jmMenu.add(itemBack);

        jMenuBar.add(jmMenu);

        jmHelp.setText("Help");

        itemHelpManual.setText("Help (User manual)");
        jmHelp.add(itemHelpManual);

        jMenuBar.add(jmHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearSelection;
    private javax.swing.JButton btnConfirmSelection;
    private javax.swing.JButton btnIncludeAll;
    private javax.swing.JMenuItem itemBack;
    private javax.swing.JMenuItem itemHelpManual;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JPanel jpnBuoyVariables;
    private javax.swing.JScrollPane jscrBuoyVariables;
    private javax.swing.JTable tblBuoyVariables;
    // End of variables declaration//GEN-END:variables
}
