/*
SPAMDA: Software for Pre-processing and Analysis of Meteorological DAta to build datasets

Copyright (c) 2017-2018 by AYRNA Research Group. https://www.uco.es/ayrna/
	Authors: 
		Antonio Manuel Gomez Orellana, Juan Carlos Fernandez Caballero,
		Manuel Dorado Moreno, Pedro Antonio Gutierrez Peña and 
		Cesar Hervas Martinez.

This program is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program,
in the file COPYING. If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7:
1. Redistributions of source code, with or without modification, must retain
the above full copyright notice as author attributions.

2. Redistributions in binary form and/or the use of the documentation,
with or without modification, must reproduce the above full copyright notice
as author attributions in the documentation and/or materials provided with
the distribution.

3. Modified versions of source code and/or documentation, as well as binary
distributions, must be marked in reasonable ways as different from the original version.

4. Neither name of copyright holders nor the names of its contributors may be used
to endorse or promote products derived from this software for publicity purposes
without specific prior written permission.

5. Redistribution and/or use of source code, binary format and documentation,
with or without modification, could require indemnification of licensors
and authors by anyone who conveys the material (or modified versions of it)
with contractual assumptions of liability to the recipient, for any liability
that these contractual assumptions directly impose on those licensors and authors.

SPAMDA uses some external libraries. You can see their respective notices about license,
copyright and disclaimer in the following files. For a more complete information about
such licenses, see the distributions provided by their authors:
-Library NetCDF Java, version 4.6.10
	Notice of license in the file NetCDF-LICENSE
-Library SLF4J, version 1.7.25
	Notice of license in the file SLF4J-LICENSE
-Library WEKA, version 3.8.1
	Notice of license in the file WEKA-LICENSE

Contact information:
Juan Carlos Fernandez Caballero, PhD.
email: jfcaballero[at]uco[dot]es
Address: University of Cordoba, Department of Computer Science
and Numerical Analysis, AYRNA Research Group, Rabanales Campus,
Einstein Building, 3rd floor. Road Madrid-Cadiz, Km 396-A.
14071 - Cordoba (Spain).
 */

package view;

import controller.ControllerViewSelectReanalysisFiles;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.interfaces.InterfaceViewSelectReanalysisFiles;
import javax.swing.table.DefaultTableCellRenderer;


/**
 * This class defines the view to select the reanalysis data files to use in the matching process.
 * 
 */
public class SelectReanalysisFiles extends javax.swing.JDialog implements InterfaceViewSelectReanalysisFiles {
        
    /* Generated by NetBeans. */
    private static final long serialVersionUID = 7140520961319603420L;
    

    /**
     * Creates new dialog ManageReanalysisData
     * 
     * @param parent Jframe that creates this dialog.
     * @param modal Indicates if the dialog is modal or not.
     */
    public SelectReanalysisFiles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        /* Sets columns size (grid with information about reanalysis data) . */
        tblReanalysisFiles.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblReanalysisFiles.getColumnModel().getColumn(1).setPreferredWidth(250);
        tblReanalysisFiles.getColumnModel().getColumn(2).setPreferredWidth(125);
        tblReanalysisFiles.getColumnModel().getColumn(3).setPreferredWidth(82);
        tblReanalysisFiles.getColumnModel().getColumn(4).setPreferredWidth(84);
        tblReanalysisFiles.getColumnModel().getColumn(5).setPreferredWidth(150);
        tblReanalysisFiles.getColumnModel().getColumn(6).setPreferredWidth(150);
        tblReanalysisFiles.getColumnModel().getColumn(7).setPreferredWidth(95);
        tblReanalysisFiles.getColumnModel().getColumn(8).setPreferredWidth(95);
        tblReanalysisFiles.getColumnModel().getColumn(9).setPreferredWidth(100);
        tblReanalysisFiles.getColumnModel().getColumn(10).setPreferredWidth(95);
        tblReanalysisFiles.getColumnModel().getColumn(11).setPreferredWidth(65);

    }
    
    
    /* Methods of InterfaceViewSelectReanalysisFiles */

    

    @Override
    public void setController(ControllerViewSelectReanalysisFiles controller){

        /* Menu items. */        
        itemBack.addActionListener(controller);
        itemHelpManual.addActionListener(controller);
        
        
        /* Buttons. */
        btnConfirmSelection.addActionListener(controller);
        btnBack.addActionListener(controller);
        
        
        /* Tables. */
        tblReanalysisFiles.addMouseListener(controller);
        tblReanalysisFiles.getSelectionModel().addListSelectionListener(controller);

    }

    
    @Override
    public void showView(){
        
        /* Shows the view. */    
        
        this.setVisible(true);
    
    }

    
    @Override
    public void closeView(){
    
        /* Closes the view. */
        this.dispose();
        
    }    
    
    
    @Override
    public DefaultTableModel getModelReanalysisFiles(){
    
        /* Returns Model of the table that will show the information about reanalysis data. */
        return (DefaultTableModel) tblReanalysisFiles.getModel();
        
    }
    
    
    @Override
    public void setModelReanalysisFiles(DefaultTableModel datamodel){
        
        /* Shows the information received about each file. */
        
        tblReanalysisFiles.setModel(datamodel);
        
    }
                       
    
    @Override
    public void setTblReanalysisFilesCellRenderer(DefaultTableCellRenderer tableCellRenderer){
        
        /* Sets tableCellRenderer for tblReanalysisFiles. */
        
        tblReanalysisFiles.setDefaultRenderer(Object.class, tableCellRenderer);        
        
    }
    
    
    @Override
    public void tblReanalysisFilesRepaint(){
        
        /* Repaints tblReanalysisFiles. */
        
        tblReanalysisFiles.repaint();
        
    }
            
    
    @Override
    public int getSelectedRow(){
        
        /* Gets the selected row. */
        
        return tblReanalysisFiles.getSelectedRow();
    
    }
    
    
    @Override
    public int getSelectedColumn(){
        
        /* Gets the selected column. */
        
        return tblReanalysisFiles.getSelectedColumn();
    
    }
    
   
    @Override
    public void moveColumnTo(int indexFrom, int indexTo){
        
        /* Moves column from indexFrom to indexTo. */
        
        tblReanalysisFiles.moveColumn(indexFrom, indexTo);        
    
    }
    

    @Override
    public void setEnabledConfirmSelection(boolean enabled){
    
        /* Sets Enabled/Disabled: Confirm selection */
        
        btnConfirmSelection.setEnabled(enabled);

    }    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedMain = new javax.swing.JTabbedPane();
        jpnFiles = new javax.swing.JPanel();
        jscrReanalysisFiles = new javax.swing.JScrollPane();
        tblReanalysisFiles = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnConfirmSelection = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();
        itemBack = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        itemHelpManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPAMDA 1.0-Select reanalysis data files to use in matching process");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        jpnFiles.setRequestFocusEnabled(false);

        jscrReanalysisFiles.setBorder(null);

        tblReanalysisFiles.setBorder(null);
        tblReanalysisFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "File name", "Variable", "# Instances", "# Nodes of reanalysis", "Time from", "Time to", "Latitude from", "Latitude to", "Longitude from", "Longitude to", "Selected"
            }
        ) {

            /* Generated by NetBeans. */
            private static final long serialVersionUID = -6158042587124966771L;

            Class<?>[] types = new Class<?> [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReanalysisFiles.setToolTipText("Click on a reanalysis data file to show compatibles files in cyan color");
        tblReanalysisFiles.setName("tblReanalysisFiles"); // NOI18N
        tblReanalysisFiles.getTableHeader().setReorderingAllowed(false);
        jscrReanalysisFiles.setViewportView(tblReanalysisFiles);
        if (tblReanalysisFiles.getColumnModel().getColumnCount() > 0) {
            tblReanalysisFiles.getColumnModel().getColumn(0).setMinWidth(0);
            tblReanalysisFiles.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblReanalysisFiles.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        tblReanalysisFiles.getAccessibleContext().setAccessibleName("");

        btnBack.setText("Back");
        btnBack.setToolTipText("Back to Matching configuration");

        btnConfirmSelection.setText("Confirm selection");
        btnConfirmSelection.setToolTipText("Confirm reanalysis data files selection and back to Matching configuration");

        javax.swing.GroupLayout jpnFilesLayout = new javax.swing.GroupLayout(jpnFiles);
        jpnFiles.setLayout(jpnFilesLayout);
        jpnFilesLayout.setHorizontalGroup(
            jpnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrReanalysisFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFilesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmSelection)))
                .addContainerGap())
        );
        jpnFilesLayout.setVerticalGroup(
            jpnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscrReanalysisFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jpnFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnConfirmSelection))
                .addContainerGap())
        );

        jTabbedMain.addTab("Reanalysis data", jpnFiles);

        jmMenu.setText("Menu");

        itemBack.setText("Back");
        itemBack.setToolTipText("Back to Matching");
        jmMenu.add(itemBack);

        jMenuBar.add(jmMenu);

        jmHelp.setText("Help");

        itemHelpManual.setText("Help (User manual)");
        jmHelp.add(itemHelpManual);

        jMenuBar.add(jmHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmSelection;
    private javax.swing.JMenuItem itemBack;
    private javax.swing.JMenuItem itemHelpManual;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JTabbedPane jTabbedMain;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JPanel jpnFiles;
    private javax.swing.JScrollPane jscrReanalysisFiles;
    private javax.swing.JTable tblReanalysisFiles;
    // End of variables declaration//GEN-END:variables
}
